[env:adafruit_feather_esp32s3]
platform  = espressif32
board     = adafruit_feather_esp32s3
framework = arduino

; 4 MB flash, 2 MB PSRAM
board_build.flash_size  = 4MB
board_build.psram       = enabled

lib_deps =
    NimBLE-Arduino   ; Lightweight BLE stack for ESP32

monitor_speed = 115200
